name: your_project_name
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/waiting.png

#  fonts:
#    - family: OpenSans
#      fonts:
#        - asset: assets/fonts/OpenSans-Regular.tff
#        - asset: assets/fonts/OpenSans-Regular.tff
#          weight: 700
